export const pharmaceuticals = [
  {
    id: 1,
    title: "Ashwagandha Extract Tablets",
    imageUrl: "/images/common/new_arrival.png",
    price: 420.0,
    originalPrice: 700.0,
    discount: 40,
    brand: "Himalaya",
    slug: "himalaya",
    rating: 4.5,
    url: "/product/ashwagandha-extract-tablets",
    isQuickShip: true,
    isSale: true,
  },
  {
    id: 2,
    title: "Chyawanprash",
    imageUrl: "/images/common/new_arrival.png",
    price: 450.0,
    originalPrice: 600.0,
    discount: 25,
    brand: "Dabur",
    slug: "dabur",
    rating: 4.5,
    url: "/product/chyawanprash",
    isQuickShip: false,
    isSale: false,
  },
  {
    id: 3,
    title: "Tulsi Extract Capsules",
    imageUrl: "/images/common/new_arrival.png",
    price: 420.0,
    originalPrice: 700.0,
    discount: 40,
    brand: "Organic India",
    slug: "organic-india",
    rating: 4.5,
    url: "/product/tulsi-extract-capsules",
    isQuickShip: true,
    isSale: true,
  },
  {
    id: 4,
    title: "Amla Juice",
    imageUrl: "/images/common/new_arrival.png",
    price: 450.0,
    originalPrice: 600.0,
    discount: 25,
    brand: "Patanjali",
    slug: "patanjali",
    rating: 4.5,
    url: "/product/amla-juice",
    isQuickShip: false,
    isSale: false,
  },
  {
    id: 5,
    title: "Neem Tablets",
    imageUrl: "/images/common/new_arrival.png",
    price: 420.0,
    originalPrice: 700.0,
    discount: 40,
    brand: "Himalaya",
    slug: "himalaya",
    rating: 4.5,
    url: "/product/neem-tablets",
    isQuickShip: true,
    isSale: true,
  },
  {
    id: 6,
    title: "Honey",
    imageUrl: "/images/common/new_arrival.png",
    price: 450.0,
    originalPrice: 600.0,
    discount: 25,
    brand: "Dabur",
    slug: "dabur",
    rating: 4.5,
    url: "/product/honey",
    isQuickShip: false,
    isSale: false,
  },
];

export const personalCare = [
  {
    id: 1,
    title: "Ayurvedic Face Wash",
    imageUrl: "/images/common/new_arrival.png",
    price: 350.0,
    originalPrice: 500.0,
    discount: 30,
    brand: "Himalaya",
    slug: "himalaya",
    rating: 4.3,
    url: "/product/ayurvedic-face-wash",
    isQuickShip: true,
    isSale: false,
  },
  {
    id: 2,
    title: "Herbal Shampoo",
    imageUrl: "/images/common/new_arrival.png",
    price: 280.0,
    originalPrice: 400.0,
    discount: 30,
    brand: "Patanjali",
    slug: "patanjali",
    rating: 4.7,
    url: "/product/herbal-shampoo",
    isQuickShip: true,
    isSale: true,
  },
];

export const babyCare = [
  {
    id: 1,
    title: "Baby Massage Oil",
    imageUrl: "/images/common/new_arrival.png",
    price: 320.0,
    originalPrice: 450.0,
    discount: 29,
    brand: "Himalaya",
    slug: "himalaya",
    rating: 4.9,
    url: "/product/baby-massage-oil",
    isQuickShip: true,
    isSale: false,
  },
  {
    id: 2,
    title: "Baby Soap",
    imageUrl: "/images/common/new_arrival.png",
    price: 120.0,
    originalPrice: 180.0,
    discount: 33,
    brand: "Himalaya",
    slug: "himalaya",
    rating: 4.6,
    url: "/product/baby-soap",
    isQuickShip: false,
    isSale: true,
  },
];

export const mensWellness = [
  {
    id: 1,
    title: "Men's Face Wash",
    imageUrl: "/images/common/new_arrival.png",
    price: 250.0,
    originalPrice: 350.0,
    discount: 29,
    brand: "Patanjali",
    slug: "patanjali",
    rating: 4.2,
    url: "/product/mens-face-wash",
    isQuickShip: false,
    isSale: false,
  },
  {
    id: 2,
    title: "Men's Hair Oil",
    imageUrl: "/images/common/new_arrival.png",
    price: 320.0,
    originalPrice: 450.0,
    discount: 29,
    brand: "Dabur",
    slug: "dabur",
    rating: 4.4,
    url: "/product/mens-hair-oil",
    isQuickShip: true,
    isSale: true,
  },
];

export const womensWellness = [
  {
    id: 1,
    title: "Women's Face Cream",
    imageUrl: "/images/common/new_arrival.png",
    price: 380.0,
    originalPrice: 550.0,
    discount: 31,
    brand: "Vicco",
    slug: "vicco",
    rating: 4.7,
    url: "/product/womens-face-cream",
    isQuickShip: true,
    isSale: false,
  },
  {
    id: 2,
    title: "Women's Hair Mask",
    imageUrl: "/images/common/new_arrival.png",
    price: 420.0,
    originalPrice: 600.0,
    discount: 30,
    brand: "Dabur",
    slug: "dabur",
    rating: 4.8,
    url: "/product/womens-hair-mask",
    isQuickShip: false,
    isSale: true,
  },
];

export const bodyCare = [
  {
    id: 1,
    title: "Body Lotion",
    imageUrl: "/images/common/new_arrival.png",
    price: 299.0,
    originalPrice: 399.0,
    discount: 25,
    brand: "Haldiram's",
    slug: "haldirams",
    rating: 4.5,
    url: "/product/body-lotion",
    isQuickShip: true,
    isSale: true,
  },
  {
    id: 2,
    title: "Body Scrub",
    imageUrl: "/images/common/new_arrival.png",
    price: 350.0,
    originalPrice: 450.0,
    discount: 22,
    brand: "Jiva",
    slug: "jiva",
    rating: 4.3,
    url: "/product/body-scrub",
    isQuickShip: false,
    isSale: false,
  },
];

export const oralHealth = [
  {
    id: 1,
    title: "Herbal Toothpaste",
    imageUrl: "/images/common/new_arrival.png",
    price: 150.0,
    originalPrice: 200.0,
    discount: 25,
    brand: "Dabur",
    slug: "dabur",
    rating: 4.6,
    url: "/product/herbal-toothpaste",
    isQuickShip: true,
    isSale: false,
  },
  {
    id: 2,
    title: "Mouthwash",
    imageUrl: "/images/common/new_arrival.png",
    price: 220.0,
    originalPrice: 280.0,
    discount: 21,
    brand: "Baidyanath",
    slug: "baidyanath",
    rating: 4.4,
    url: "/product/mouthwash",
    isQuickShip: false,
    isSale: true,
  },
];

// Define brand data interface
export interface Brand {
  slug: string;
  name: string;
  bannerImage: string;
  reviewCount: number;
}

// Export brands data
export const brands: Record<string, Brand> = {
  himalaya: {
    slug: "himalaya",
    name: "Himalaya",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 115,
  },
  dabur: {
    slug: "dabur",
    name: "Dabur",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 87,
  },
  patanjali: {
    slug: "patanjali",
    name: "Patanjali",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 103,
  },
  "organic-india": {
    slug: "organic-india",
    name: "Organic India",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 72,
  },
  haldirams: {
    slug: "haldirams",
    name: "Haldiram's",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 95,
  },
  everest: {
    slug: "everest",
    name: "Everest",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 68,
  },
  jiva: {
    slug: "jiva",
    name: "Jiva",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 54,
  },
  vicco: {
    slug: "vicco",
    name: "Vicco",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 76,
  },
  "aadya-naturals": {
    slug: "aadya-naturals",
    name: "Aadya Naturals",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 42,
  },
  baidyanath: {
    slug: "baidyanath",
    name: "Baidyanath",
    bannerImage: "/images/brand/banner.png",
    reviewCount: 89,
  },
};
